### ISSUE TITLE
Icons for newer cosmetics

### ISSUE THREAD

**Issue by ItsGreyToday** [BranchieDev/Branch-Vanities#1]
Are there really no icons/thumbnails for the newer cosmetics?
![AC Preview](https://i.imgur.com/kwml7Gj.gif)

**Comment by BranchieDev** [comment]
Currently yes, sorry. I'll get to it ASAP.

**Comment by ItsGreyToday** [comment]
> Currently yes, sorry. I'll get to it ASAP.

No rush, thanks for the awesome cosmetics!

**Comment by BranchieDev** [comment]
Done! Thank you for the feedback.
